services:
    # Metadata Drivers
    trappar_alice_generator.metadata.file_locator:
        public: false
        class: Metadata\Driver\FileLocator

    Trappar\AliceGenerator\Metadata\Driver\YamlDriver:
        public: false
        arguments: ['@trappar_alice_generator.metadata.file_locator']

    Trappar\AliceGenerator\Metadata\Driver\AnnotationDriver:
        public: false
        arguments: ['@annotation_reader']

    trappar_alice_generator.metadata.chain_driver:
        public: public
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@Trappar\AliceGenerator\Metadata\Driver\YamlDriver', '@Trappar\AliceGenerator\Metadata\Driver\AnnotationDriver']

    trappar_alice_generator.metadata.lazy_loading_driver:
        public: false
        class: Metadata\Driver\LazyLoadingDriver
        arguments:
            - '@service_container'
            - 'trappar_alice_generator.metadata.chain_driver'

    # Metadata Factory
    trappar_alice_generator.metadata.factory:
        public: false
        class: Metadata\MetadataFactory
        arguments: ['@trappar_alice_generator.metadata.lazy_loading_driver']

    # Metadata Resolvers Faker
    Trappar\AliceGenerator\Metadata\Resolver\Faker\ArrayFakerResolver:
        public: false

    Trappar\AliceGenerator\Metadata\Resolver\Faker\CallbackFakerResolver:
        public: false

    Trappar\AliceGenerator\Metadata\Resolver\Faker\NoArgFakerResolver:
        public: false

    Trappar\AliceGenerator\Metadata\Resolver\Faker\ValueAsArgFakerResolver:
        public: false

    Trappar\AliceGeneratorBundle\Metadata\Resolver\Faker\ServiceFakerResolver:
        public: false
        arguments: ['@service_container']

    # Metadata Resolvers
    Trappar\AliceGenerator\Metadata\Resolver\MetadataResolver:
        public: false
        arguments:
            -
                - '@Trappar\AliceGenerator\Metadata\Resolver\Faker\ArrayFakerResolver'
                - '@Trappar\AliceGenerator\Metadata\Resolver\Faker\CallbackFakerResolver'
                - '@Trappar\AliceGenerator\Metadata\Resolver\Faker\NoArgFakerResolver'
                - '@Trappar\AliceGenerator\Metadata\Resolver\Faker\ValueAsArgFakerResolver'
                - '@Trappar\AliceGeneratorBundle\Metadata\Resolver\Faker\ServiceFakerResolver'

    # Persisters
    Trappar\AliceGeneratorBundle\Persister\DoctrinePersister:
        public: false
        arguments: ['@doctrine']

    # Object Handlers
    Trappar\AliceGenerator\ObjectHandler\CollectionHandler:
        public: false

    Trappar\AliceGenerator\ObjectHandler\DateTimeHandler:
        public: false

    # Object Handler Registries
    Trappar\AliceGenerator\ObjectHandlerRegistry:
        public: false
        arguments:
            -
                - '@Trappar\AliceGenerator\ObjectHandler\CollectionHandler'
                - '@Trappar\AliceGenerator\ObjectHandler\DateTimeHandler'

    # Yaml Writer
    Trappar\AliceGenerator\YamlWriter:
        public: false

    # Fixture Generator
    Trappar\AliceGenerator\ValueVisitor:
        public: false
        arguments:
            - '@trappar_alice_generator.metadata.factory'
            - '@Trappar\AliceGeneratorBundle\Persister\DoctrinePersister'
            - '@Trappar\AliceGenerator\Metadata\Resolver\MetadataResolver'
            - '@Trappar\AliceGenerator\ObjectHandlerRegistry'


    Trappar\AliceGenerator\FixtureGenerator:
        public: true
        arguments:
            - '@Trappar\AliceGenerator\ValueVisitor'
            - '@Trappar\AliceGenerator\YamlWriter'

    # Command
    trappar_alice_generator.command.generate_fixtures:
        class: Trappar\AliceGeneratorBundle\Command\GenerateFixturesCommand
        tags: [ { name: console.command } ]
        arguments:
            - '@doctrine'
            - '@kernel'
            - '@Trappar\AliceGenerator\FixtureGenerator'
            - '@filesystem'
